sonar.projectKey=Les-Chauffagistes_history-server
sonar.projectName=History Server
sonar.organization=les-chauffagistes

sonar.sources=src,main.py,init.py
sonar.tests=tests
sonar.python.version=3

sonar.cpd.exclusions=tests/**