name: CI
 
on:
  push:
    branches: ["**"]
    tags: ["v*.*.*"]
  pull_request:

 
jobs:
  test:
    uses: Les-Chauffagistes/deploy/.github/workflows/test.yml@develop
    with:
      python-version: '3.13'
    secrets: inherit

  build-push:
    if: github.event_name == 'push'
    needs: test
    uses: Les-Chauffagistes/deploy/.github/workflows/build.yml@develop
    with:
      service-name: history-server
    secrets: inherit