name: CI
 
on:
  push:
    branches: ["**"]
    tags: ["v*.*.*"]
  pull_request:

 
jobs:
  build-push:
    uses: les-chauffagistes/deploy/.github/workflows/build.yml@develop
    with:
      service-name: history-server
    secrets:
      REGISTRY_USER:     ${{ secrets.REGISTRY_USER }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      ORG_PAT:           ${{ secrets.ORG_PAT }}
 